services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 9090:27017
    volumes:
      - mongo_data_container:/data/db
    networks:
      - product-network

  dotnet_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
          ConnectionStrings__ControlePedidosDB: mongodb://admin:123@localhost:27017/?retryWrites=false
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - mongodb_container
    networks:
      - product-network

networks:
  product-network:
    driver: bridge

volumes:
      mongo_data_container:

