global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using ControlePedidos.Common.Exceptions;
global using ControlePedidos.Common.Entities;
global using ControlePedidos.Pedido.Domain.Enums;
global using ControlePedidos.Pedido.Domain.Entities;