apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apptc-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apptc-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50 # 50% de uso de CPU
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 70 # 70% de uso de memória